# Generated by Django 4.2.2 on 2024-05-06 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lobby', '0002_user_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='creador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creadorAsignatura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='creador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creadorEjercicio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serie',
            name='creador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creadorSerie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='creador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('DOING', 'Doing'), ('DONE', 'Done'), ('PAUSED', 'Paused')], default='TODO', max_length=6),
        ),
    ]
