# Generated by Django 4.2.2 on 2024-05-06 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lobby', '0003_asignatura_creador_ejercicio_creador_serie_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creadorAsignatura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creadorEjercicio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serie',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creadorSerie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
    ]
